---
- name: Fetch instance information
  os_server_info:
    cloud: openstack
    region_name: regionOne
  register: r_os_servers
  
- name: Delete instances
  os_server:
    cloud: openstack
    state: absent
    name: "{{ item.name }}"
  loop: "{{ r_os_servers }}"
  loop_control:
    label: "{{ item.name }}"
