---
# tasks file for osp-facts
- name: Fetch Instance Info
  os_server_info:
    cloud: openstack
    region_name: regionOne
  register: r_os_servers


- name: show my register
  debug:
    var: r_os_servers


- name: Add host 
  add_host: 
    name: "{{ item.public_v4 }}" 
    group: 
      - "{{ item.metadata.group }}"
      - "{{ item.metadata.deployment_name }}"
  with_items: "{{ r_os_servers.openstack_servers }}"
